### ISSUE TITLE
Create a `usage` subroutine for all sub commands

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVAC-Seq#10]
For consistency set up the usage docs the same way in all sub commands.

**Comment by jasonwalker80** [comment]
@susannasiebert this is somewhat relevant to our discussion about the CLI. For instance do we make our own command base class as was done with Genome, UR, etc. or since we are moving forward with python, do one of these libraries make sense:
http://docs.python-guide.org/en/latest/scenarios/cli/

docopt specfically reminded me of this issue for defining common sub-command usage docs.

**Comment by susannasiebert** [comment]
Yes, I think doctopt and Cliff look promising. argparse would be the "standard" way to do it if we don't want to rely on an outside library. I think we need to consider dependencies on non-standard libraries for what we can install ourselves on our system here and also what we would then require the users to install.

**Comment by jasonwalker80** [comment]
This will be covered by #19.
