### ISSUE TITLE
Mouse alleles listed in pvacseq valid_alleles not working

### ISSUE THREAD

**Issue by strixeh** [griffithlab/pVAC-Seq#114]
Hi,

There seem to be some problem with way to write mouse alleles. 

According to `pvacseq valid_alleles` (pvacseq 3.0.0), mouse alleles are written as `H-2 Ld`.
When running `./netMHC -A`, `H-2-Ld` is indicated as the right format (NetMHC 3.4).

Neither of these works. I tried a couple of different things...:

```
>pvacseq run /home/strix/pvacseq/input/claire_anno.vcf test2 H-2-Ld 9 NetMHC /home/strix/pvacseq/output/test2
Allele H-2-Ld not valid. Run `pvacseq valid_alleles` for a list of valid allele names.
```
```
>pvacseq run /home/strix/pvacseq/input/claire_anno.vcf test2 H-2 Ld 9 NetMHC /home/strix/pvacseq/output/test2
usage: pvacseq run [-h] [-l PEPTIDE_SEQUENCE_LENGTH] [-t] [-m {lowest,median}]
                   [-b BINDING_THRESHOLD] [-c MINIMUM_FOLD_CHANGE]
                   input_file sample_name allele epitope_length
                   {NetMHC,NetMHCcons,NetMHCpan,PickPocket,SMM,SMMPMBEC}
                   [{NetMHC,NetMHCcons,NetMHCpan,PickPocket,SMM,SMMPMBEC} ...]
                   output_dir
pvacseq run: error: argument epitope_length: invalid <lambda> value: 'Ld'
```
```
>pvacseq run /home/strix/pvacseq/input/claire_anno.vcf test2 'H-2 Ld' 9 NetMHC /home/strix/pvacseq/output/test2
Converting VCF to TSV
Completed
Generating Variant Peptide FASTA File
Completed
Generating FASTA Key File
Completed
Running IEDB on Allele H-2 Ld and Epitope Length 9 with Method NetMHC
Error posting request to IEDB.

	
list indices must be integers, not str
```

Any ideas?

Thanks,
Nils

**Comment by susannasiebert** [comment]
So there are multiple things going on here. If an argument to a python command has a space in it, it needs to be enclosed in quotes, which you did in your last call. However, it seems like the allele in this format is not actually accepted by the IEDB RESTful interface which is why you're getting the `list indices must be integers, not str` error (which is what the IEDB request returns in this case). IEDB expects the allele to be `H-2-Ld` but pvacseq prohibits this as an invalid allele. We added this to make sure that the alleles passed to IEDB are in the correct format but it seems like the list we have is not quite correct and needs to be fixed. We'll try to put a hotfix out as soon as possible.

**Comment by strixeh** [comment]
Ah ok, I understand. Thanks for the help, looking forward to the hotfix.

**Comment by susannasiebert** [comment]
We released a hotfix (version 3.0.2). Unfortunately we had to skip a version number. Hope that doesn't cause any confusion. The hotfix contains fixes for both this issue and #113

**Comment by strixeh** [comment]
Hi! Thanks for working so fast. It is up and running now...! Im predicting using a short list of 3 mutations in mouse, using all prediction algorithms. I will let you know if I find something funny :). Thanks!

**Comment by susannasiebert** [comment]
You're welcome. I'll resolve this issue and #113 but feel free to make a new issue for any problems you might encounter in the future.
