### ISSUE TITLE
Not getting any prediction data in files for frameshift variants

### ISSUE THREAD

**Issue by strixeh** [griffithlab/pVAC-Seq#143]
Hi, 

I am running `pvacseq run pat4_4A_frameshift.vcf.anno pat4_4a_frameshift HLA-A*24:02 9 NetMHC /pat4_4a_frameshift -b 500 -s 100 --keep-tmp-files` 

but my .combined.parsed.tsv and .filtered.tsv are empty. There are data in my temporary files however. Attached is folder with input vcf file, and all output files.

Thanks,
Nils

[pat4_4a_frameshift.zip](https://github.com/griffithlab/pVAC-Seq/files/400449/pat4_4a_frameshift.zip)

**Comment by susannasiebert** [comment]
It looks like something might've gone awry with your VEP annotations. In your VCF none of the Downstream fields are filled in. When you look at your fasta you will see that all of the MT entries only contain 10 wildtype amino acids before the mutation and no downstream sequence. During parsing all entries where the wildtype and the mutant subsequences are identical will be parsed out since they contain no mutant amino acids.

I would try to re-annotate your VCF with VEP. Maybe there was an error the first time around that got missed? I can't really think of a situation where there wouldn't be a downstream sequence for these. But then again, I'm not a biologist. It seems unlikely to me that none them would have downstream sequences. It might also be worthwhile to just manually inspect a few of these variants to confirm whether or not they should have a downstream sequence. The folks at ENSEMBL might also be able to shed some light on what is going on here. 

One thing we can do on our end is to exclude frameshifts without a downstream sequence from being included in the fasta. That way there isn't any confusion about why they weren't processed downstream.

**Comment by strixeh** [comment]
Hi Susanna, thanks for the reply. I tried rerunning the VEP annotation on the files, and then my VCF was correctly annotated with Downstream protein info. I must have missed an error or something else. I will make sure to look over my VEP annotated VCF files in the future before using them as input in pvacseq.

Thanks again for the brilliant help and quick replies from you.

Best,
Nils

**Comment by susannasiebert** [comment]
I'm glad VEP worked correctly the second time around. I'll resolve this issue.
