### ISSUE TITLE
Add step to calculate self-similarity of MT epitope

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVAC-Seq#222]
Take the peptide sequence and do some sort of similarity search against the ref proteome (BLAST) to see if the peptide naturally exists in the body. If so, it wouldn't be recognized as "foreign" antigen.

**Comment by strixeh** [comment]
I think this kind of search might prove beneficial. However, I wonder if you don't want to search the normal bam file instead of a human ref genome to remove any possibility of having a germ-line mutation with the same sequence as the somatic mutation that yield a peptide with low IC50 value. I dont know how likely this is though...

**Comment by chrisamiller** [comment]
Blasting sequences against a personal proteome is something that we've discussed this in the past, and it's on our to-do list for the future. Blasting against the reference proteome is step 1, and incorporating germline events will be after that.
