### ISSUE TITLE
Taking too long

### ISSUE THREAD

**Issue by patidarr** [griffithlab/pVAC-Seq#255]
Hi,

I submitted the following command yesterday evening but this is still running.
pvacseq run -e 8,9,10,11 68_T1D_E.final.vcf CL0068_T1D_E ${allele} {NNalign,NetMHC,NetMHCIIpan,NetMHCcons,NetMHCpan,PickPocket,SMM,SMMPMBEC,SMMalign} NeoAntigen/

where I have only 4 $allele =HLA-A*02:01,HLA-B*15:03,HLA-C*16:01,HLA-C*02:02
I did printed some STDOUT messages in the beginning but for the last 13 hrs its silent. I assume this is not normal...

an suggestions on how do I solve this?

Thanks,
Rajesh

**Comment by susannasiebert** [comment]
What's the last status message it printed to STDOUT? You can probably just kill this job and resubmit. if you're using the same command with the same output directory it should pick up where it got hung up.

**Comment by patidarr** [comment]
Parsing IEDB Output for Allele HLA-B*15:03 and Epitope Length 10 - Entries 1-200
Completed
Processing entries for Allele HLA-B*15:03 and Epitope Length 11 - Entries 1-200
Running IEDB on Allele HLA-B*15:03 and Epitope Length 11 with Method NetMHC - Entries 1-200
Completed
Running IEDB on Allele HLA-B*15:03 and Epitope Length 11 with Method NetMHCcons - Entries 1-200
Completed
Running IEDB on Allele HLA-B*15:03 and Epitope Length 11 with Method NetMHCpan - Entries 1-200


I will try killing and resubmitting the job and see if I can finish it up or not.

**Comment by susannasiebert** [comment]
If this problem persist for this portion of entries you might want to see what type of variants are in that portion by examining the corresponding fasta file in the `NeoAntigen/MHC_Class_I/tmp` directory. It might be that there is a very long frameshift that causes IEDB to get hung up. If this is the case you could try to set the `-d` option to a lower value.

You can also try and set the `-s` option to a lower value which will reduce the number of fasta entries that get submitted to IEDB at the same time.

When you add either of these options you will want to delete the existing output directory or write to a different one because these options change what gets submitted to IEDB and things might get messed up if there are output files that already exist.

**Comment by patidarr** [comment]
As I am using strelka for variant calling which hardly call long indels, I suspect it could be the # of fasta entries that could potentially solve this. 

Thanks a lot, I will try changing `-s` and see if I can get successful result on this patient.

**Comment by patidarr** [comment]
Hi,

i added the -s parameter and resubmitted a job but getting following error:
Processing entries for Allele HLA-B*15:03 and Epitope Length 9 - Entries 1-50
Running IEDB on Allele HLA-B*15:03 and Epitope Length 9 with Method NetMHC - Entries 1-50
Completed
Running IEDB on Allele HLA-B*15:03 and Epitope Length 9 with Method NetMHCcons - Entries 1-50
Completed
Running IEDB on Allele HLA-B*15:03 and Epitope Length 9 with Method NetMHCpan - Entries 1-50
IEDB: Retry 0 of 5
IEDB: Retry 1 of 5
IEDB: Retry 2 of 5
IEDB: Retry 3 of 5
IEDB: Retry 4 of 5


unable to open database file

**Comment by susannasiebert** [comment]
I haven't seen this error but something seems to be wrong with IEDB. I can't make requests to their RESTful API from the command line.

IEDB is in the process of phasing out their current RESTful API and moving to a new URL. The new URL works. We are in the process of updating pVAC-Seq to this new URL. I'm not sure if the error you are seeing is because IEDB stopped supporting their old URL before the announced deprecation date or whether this is an intermittent issue and the URL will work again later.

I will fast track a new release that will update the URL.

**Comment by patidarr** [comment]
Updated version will be great, it will also solve the invalid allele issue I am having as well.

Thanks,

**Comment by susannasiebert** [comment]
It looks like the RESTful API is back up and running. You should be able to run pVAC-Seq again without any changes on our end. We're still planning on making a new release soon.

**Comment by patidarr** [comment]
Thanks, I resubmitted the job, hopefully finish without hitch, still wait for new release as a better and more permanent solution.

**Comment by susannasiebert** [comment]
The newest release (4.0.6) updates the RESTful API URLs to the new targets.
