### ISSUE TITLE
Call to local IEDB install failed:

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#258]
Error when I submit the qsub, but in Interactive session it works,

Command Used: 
pvacseq run -b 500 -c 1 -e 9 MELA_20054_Ex_2.vcf MELA_XXX HLA-A*01:01 NetMHC NetMHCpan /working/genomeinfo/share/temp/Analysis/pVAC-Seq/pVACoutput

Error:
---
Usage: predict_binding.py method allele or [options] arg length

Following are the available choices - 
   method: ann, comblib_sidney2008, consensus, IEDB_recommended, netmhcpan, smm, smmpmbec, pickpocket, netmhccons
   allele: an allele name
   length: a length

predict_binding.py: error: incorrect number of arguments
Call to local IEDB install failed:
python2.7 /software/IEDB_MHC/IEDB_MHC-2.15.1/mhc_i/src/predict_binding.py ann HLA-A*01:01 9 /working/genomeinfo/share/temp/venkatA/Analysis/HLA_Typing/pVAC-Seq/pVACoutput/MHC_Class_I/tmp/MELA_XXX_21.fa.split_1-200
Aborting.

**Comment by susannasiebert** [comment]
A different user ran into this same error in issue #232 when running pVAC-Seq in Docker. He was able to work around it by modifying the IEDB script. His changes can be found in #232. I'm not sure if this workaround would work in your case as well but it's worth a try. I don't think there is much we can do on our end to prevent this error from happening as it seems to be related to how IEDB handles stdin.

**Comment by venkataddala** [comment]
Got that, made the changes accordingly. Hope it's running successfully.

Is there any way to multithread pvaseq run. Currently it's taking 1 CPU and taking so long time.

**Comment by susannasiebert** [comment]
Multithreading is a feature we would like to add in the future (see #162) but we aren't currently working on it. Since you are using the standalone IEDB version you could try to increase the `--fasta-size` parameter which is set to 200 by default. This limitation was mostly put into place to reduce the compute burden on the IEDB RESTful API but using standalone IEDB you should be able to use a much larger chunk size.
