### ISSUE TITLE
You don't have permission to access /tools_api/mhci/

### ISSUE THREAD

**Issue by mPiyushkumar** [griffithlab/pVAC-Seq#280]
Hi,

I am trying to run pvac-seq (version 4.0.6) with following command: 

pvacseq run -e 8,9,10,11 -c 1  S36_VarScan.snp.Somatic.hc.vcf_VEPout_Pvacseq S36_VarScan H-2-Db,H-2-Dd,H-2-Kb,H-2-Kd,H-2-Kk,H-2-Ld NetMHCpan /scratch/pmundra/Data/SNP_HC_VCF_Mouse/

However, it is producing an error: 

Error posting request to IEDB.
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /tools_api/mhci/
on this server.</p>
<hr>
<address>Apache/2.4.6 (CentOS) Server at tools-cluster-interface.iedb.org Port 80</address>
</body></html>

Can you please advise? 

Regards,
Piyush

**Comment by susannasiebert** [comment]
Your IP might've gotten blacklisted by IEDB for making too many requests which would happen if you try to process a large number of variants with many prediction algorithms, epitope lengths and/or alleles. We recommend that you install and use the standalone IEDB tools with pVAC-Seq if that is the case.

In order to remove your IP address from IEDB's blacklist you will need to put in a ticket with their [helpdesk](help.iedb.org). The newest version of pVAC-Seq (4.0.8) implements a 60 second wait between individual requests so if you upgrade to that version you might be fine running your process with the IEDB API once the IP-block is removed.

**Comment by mPiyushkumar** [comment]
Yes, indeed I was trying to use pvac-seq on multiple samples simultaneously! I will ask our administrator to install IEDB locally and upgrade the pvac-seq to the latest version. 

Thank you!
