### ISSUE TITLE
VCF contains more than one sample

### ISSUE THREAD

**Issue by cthyge** [griffithlab/pVAC-Seq#281]
Hi, 

I have encountered a problem when running your program. I run my vcf file through the pipeline, but it halts when converting to TSV, because the vcf “contains more than one sample”.

This is my process:

I have a single matched tumor and normal sample, which was mapped using BWA followed by variant calling with SamTools’ mpileup and VarScan Somatic 2.3.
Using the varscan command

`varscan somatic normal_exome.mpileup tumor_exome.mpileup sample1 --output-vcf  --somatic-p-value 0.01`

This gives me a vcf with one column for tumor and one for the normal sample, which I then pass to VEP with the following command, as per your documentation:

`perl variant_effect_predictor.pl -i input.vcf --format vcf --cache --dir ~/.vep/ --merged -o output.vcf --vcf --force_overwrite --symbol --dir_plugins ~/.vep/Plugins --plugin Downstream --plugin Wildtype --terms SO`

Finally I run pvacseq with the command;

`pvacseq run my_vcf.vcf patient1_case1 DRB1*07:01,DRB1*04:05,HLA-A*29:02,HLA-B*45:01,HLA-C*06:02 NetMHCpan NetMHCIIpan pvacseq_out -e 8,9,10,11`

which results in the error.

If I manually delete the column in the vcf-file corresponding to the normal sample, the pipeline runs without problems, but surely this is not the ideal approach.
How do you process the data to not have a column in the vcf for both normal and tumor sample?

I have not been able to find information on this neither in your article nor in the documentation.
Any help would be appreciated.

**Comment by susannasiebert** [comment]
I think the SelectVariants GATK tool might work well for splitting your VCF (https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_gatk_tools_walkers_variantutils_SelectVariants.php). From reading the documentation you will probably want to use the `-env` and `-ef` options so that non-variant loci will be excluded and the remaining alleles will be trimmed. pVAC-Seq will process all variants and alt alleles in the VCF so if after splitting you still have variants or alt alleles in your VCF that really belong to the second sample, those would be included in the pVAC-Seq report. So you want to make sure that your VCF really only includes variants and alt alleles that belong to the sample in question.

**Comment by mPiyushkumar** [comment]
I had the same problem, but resolved it by using vcftools -c TUMOR command on the varscan output. It will create a new file with only tumor information.

**Comment by susannasiebert** [comment]
I assume that you were able to solve this problem so I will close this issue but feel free to reopen if you are still having problems with subsetting your VCF.

**Comment by huangxiaogua** [comment]
@mPiyushkumar how do you use vcftools -c TUMOR command ? when you run VarScan you use vcftools -c TUMOR command ? I had got vcf file from sentieon TNseq by  online app and had the same problem. Can you tell me the details. Now, I can use vcftools to  split my VCF? Thank you

**Comment by susannasiebert** [comment]
@huangxiaogua I believe you run VCFtools after VarScan on the VCF created by VarScan. This might work: `vcftools --vcf <varscan vcf> --indv <sample name for sample to keep> -c > <output.vcf>`
