### ISSUE TITLE
Output pVAC-seq

### ISSUE THREAD

**Issue by runnerBio88** [griffithlab/pVAC-Seq#330]
Hello.

I've some question regarding the output of pVAC-seq. Sorry if any of these is a silly one.

1) When having indels and SNV in the somatic vcf file. Do I have to split this file into a indel vcf and SNV vcf, then run for each one its own bamreadcount using the options -i (indel) and -l (SNV) and then run twice pVAC-seq (one for SNV and other for indels)? This process would end with two final.tsv, one for the indels and one for the SNV.

2) I've ran pVAC-seq with my own data. I've used bamreadcount output (-b 20 -w 5), but when I check the final.tsv file I see some lines where tumor DNA, RNA and Normal DNA depth are NA. I would expect this to be filtered out as there is no data. Why is this not happening? 

3) In the final.tsv I'm assuming that the numbers that appear under the DNA/RNA depth are for those reads that have passed the filter setted up during the bamreadcount proccces. So if a base has 300 reads, but only 200 pass the filtering,  in the final.tsv will only apear as depth 200. Am I rigth?

4) I've ran pVAC-seq using alleles typed from seq2HLA and out of the ~5 HLA only one appears in the final.tsv. I assume that for the rest of the alleles no solution has been found.

Thanks for your time. Hopefully, I'll be able to run this using the data you used in your paper so I can be sure that I'm running the pipeline properly.

Once more thanks for you time.

**Comment by susannasiebert** [comment]
Thanks for your questions and for your interest in using pVAC-Seq. We're currently working on expanding our documentation to include an FAQ section so I will make sure to include my answers there as well.

1) You need to split the somatic VCF into a snv and indel one, like you described above, in order to run bam-readcount. However, when you actually run pVAC-Seq you can do so on the combined file. When including the bam-readcount files in your run you would then specify the following entries in your additional inputs yaml file (`--additional-input-file-list`):
```
tdna_snvs_coverage_file: <bam-readcount output file for tumor DNA BAM and snvs>
tdna_indels_coverage_file: <bam-readcount output file for tumor DNA BAM and indels>
```
pVAC-Seq takes care to associate each bam-readcount entry with the correct VCF variant. You may also run the snv and indel vcf separately. The output of the two final.tsv from pVAC-Seq once combined should be the same as when running it at the same time.

2) We do not filter out `NA` entries for coverage and VAF since these entires simply mean that we do not have enough information to determine whether the cutoff has been met on way or another.

3) That is correct. The depth and VAF columns are calculated from the bam-readcount output.

4) There could be a few reasons for that. The alleles you picked might've not been compatible with the prediction algorithm and/or epitope lengths chosen. In that case no calls for that allele would've been made and a status message would've printed to the screen. It could also be that all epitope predictions with those alleles got filtered out. You can check the combined.parsed.tsv file to see all called epitopes before filtering.

**Comment by runnerBio88** [comment]
Thanks for these fast and helpful answers!
