### ISSUE TITLE
wildtype amino acid sequence is real "WT"?

### ISSUE THREAD

**Issue by TotalMiss** [griffithlab/pVAC-Seq#344]
I try to use pVAC-Seq  to  identify neoantigens. I noticed there is a germline variation next to somatice mutation,and only somatice mutations were used to  identify neoantigens. 
I am not sure wildtype amino acid sequence was predicted use germline information or not?Shouldn't I use germline variation first?

**Comment by susannasiebert** [comment]
pVACseq currently only evaluates one somatic mutation at a time and does not take into account proximal germline or somatic variants. However, we are working on a feature to support these cases, which should be released in a couple of months.

**Comment by susannasiebert** [comment]
Please also note that this repository is deprecated and is no longer maintained. The `pvacseq` package has been superseded by the `pvactools` package and the repository has moved to https://github.com/griffithlab/pVACtools where all new feature development is happening. In order to have the most up-to-date features and bugfixes I highly recommend to uninstall the pvacseq package (`pip uninstall pvacseq`) and install pvactools (`pip install pvactools`). The pvacseq commands stay the same. I'm moving your issues to the pVACtools repository.

**Comment by susannasiebert** [comment]
Issue moved to [griffithlab/pVACtools #145](https://github.com/griffithlab/pVACtools/issues/145) via [**ZenHub**](https://www.zenhub.com/)
